#
# RequestController
#
requests.list:
  path: '/request/list'
  defaults:
      _controller: AppBundle:Request:list
requests.new:
  path: '/request/new'
  defaults:
      _controller: AppBundle:Request:new
requests.edit:
  path: '/request/edit/{id}'
  defaults:
      _controller: AppBundle:Request:edit
requests.remove:
  path: '/request/remove/{id}'
  defaults:
      _controller: AppBundle:Request:remove



#
# UserController
#
user.list:
  path: '/user/list'
  defaults:
      _controller: AppBundle:User:list
user.new:
  path: '/user/new'
  defaults:
      _controller: AppBundle:User:new
user.edit:
  path: '/user/edit/{id}'
  defaults:
      _controller: AppBundle:User:edit
user.remove:
  path: '/user/remove/{id}'
  defaults:
      _controller: AppBundle:User:remove



#
# CommonEntityController
#
common.list:
  path: '/{entity}/list'
  defaults:
      _controller: AppBundle:CommonEntity:list
      table_only: ''
  requirements:
      entity: 'category|department|active'

common.new:
  path: '/{entity}/new'
  defaults:
      _controller: AppBundle:CommonEntity:new
  requirements:
      entity: 'category|department|active'
common.edit:
  path: '/{entity}/edit/{id}'
  defaults:
      _controller: AppBundle:CommonEntity:edit
  requirements:
      entity: 'category|department|active'
common.remove:
  path: '/{entity}/remove/{id}'
  defaults:
      _controller: AppBundle:CommonEntity:remove
  requirements:
      entity: 'category|department|active'
