security:
    role_hierarchy:
        ROLE_ADMIN: ['ROLE_MODERATOR', 'ROLE_EXECUTOR', 'ROLE_USER']
        ROLE_MODERATOR: ['ROLE_USER']
        ROLE_EXECUTOR: ['ROLE_USER']
    access_control:
        - { path: "^/user/list", roles: ["ROLE_USER"] }
        - { path: "^/user/", roles: ["ROLE_ADMIN"] }