app:
    resource: '@AppBundle/Controller/'
    type: annotation
main_logout:
  path: '/account/logout'

 # app/config/routing_dev.yml
_errors:
  resource: "@TwigBundle/Resources/config/routing/errors.xml"
  prefix:   /_error

entity_routes:
  resource: "entity_controllers_routes.yml"



fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }