imports:
  - { resource: "entity_controllers_access_control.yml" }

# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        entity:
            entity:
                class: AppBundle\Entity\User
                property: login

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            remember_me:
                secret: %secret%
                remember_me_parameter: login[_remember_me]
            form_login:
                remember_me: true
            # submit the login form here
                check_path: /account/login

                # the user is redirected here when they need to log in
                login_path: /account/login

                # if true, forward the user to the login form instead of redirecting
                use_forward: false

                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    false

                # login failure redirecting options (read further below)
                #failure_path:    /account/login
                failure_forward: false
                failure_path_parameter: _failure_path
                #failure_handler: some.service.id
                #success_handler: some.service.id

                # field names for the username and password fields
                username_parameter: login[login]
                password_parameter: login[password]

                # csrf token options
                csrf_parameter:       login[_csrf_token]
                csrf_token_id:        authenticate
                #csrf_token_generator: my.csrf_token_generator.id

                # by default, the login form *must* be a POST, not a GET
                post_only:      true
                remember_me:    false

                # by default, a session must exist before submitting an authentication request
                # if false, then Request::hasPreviousSession is not called during authentication
                require_previous_session: true
            logout:
                path:   /account/logout
                target: /
                invalidate_session: false
                #delete_cookies:
                #    a: { path: null, domain: null }
                #    b: { path: null, domain: null }
                #handlers: [some.service.id, another.service.id]
                #success_handler: some.service.id
    encoders:
        AppBundle\Entity\User: bcrypt
