<?php
/**
 * Created by PhpStorm.
 * User: Alexey Grigoriev
 * Date: 14.09.2017
 * Time: 15:54
 */

namespace AppBundle\Form;


use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use AppBundle\Entity\Active;
use AppBundle\Entity\Department;
use Symfony\Component\Translation\Translator;

class ActiveNewEditType extends BaseNewEditType {

    private $translator;
    public function __construct(Translator $translator){
        $this->translator = $translator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('cabNumber', TextType::class, array('label'=>'form.active.number'));
        $builder->add('department', EntityType::class, array(
            'label'=>'form.active.department',
            'class'=>Department::class,
            'choice_label'=>'name',
            'choice_translation_domain'=>'messages',
            'multiple'=>false,
            'attr'=>array('data-placeholder'=>$this->translator->trans('form.active.department',[],'forms'))
        ));
        $this->addButtons($options['formUsage'],$builder, '/active/list');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefault('data_class',Active::class);
    }
}