<?php
/**
 * Created by PhpStorm.
 * User: Alexey Grigoriev
 * Date: 15.09.2017
 * Time: 11:42
 */

namespace AppBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type;
use AppBundle\Entity\Request;
use AppBundle\Entity\Active;
use AppBundle\Entity\Category;
use AppBundle\Entity\User;
use AppBundle\Entity\Comment;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class RequestNewType extends AbstractType{

    /*
     * {{ form_row(form.name) }}
    {{ form_row(form.description) }}
    {{ form_row(form.priority) }}
    {{ form_row(form.active) }}
    {{ form_row(form.file) }}
    {{ form_row(form.category) }}
    {{ form_row(form.user) }}
    {{ form_row(form.executor) }}

    {{ form_row(form.comments) }}

     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', Type\TextType::class, array('label'=>'form.request.name'));
        $builder->add('description', Type\TextAreaType::class, array(
            'label'=>'form.request.description',
            'attr'=>array('style'=>'resize:vertical;')
        ));
        $builder->add('priority', Type\ChoiceType::class, array(
            'label'=>'form.request.priority',
            'choices'=>array(
                'form.request.priority.critical'=>Request::PRIORITY_CRITICAL,
                'form.request.priority.high'=>Request::PRIORITY_HIGH,
                'form.request.priority.medium'=>Request::PRIORITY_MEDIUM,
                'form.request.priority.low'=>Request::PRIORITY_LOW
            )
        ));
        $builder->add('active', EntityType::class, array(
            'label'=>'form.request.active',
            'class'=>Active::class,
            'choice_label'=>'cabNumber',
            'group_by'=>function($val, $key, $index){
                return $val->getDepartment()->getName();
            }
        ));
        $builder->add('file', Type\FileType::class, array('label'=>'form.request.file'));
        $builder->add('category', EntityType::class, array(
            'label'=>'form.request.category',
            'class'=>Category::class,
            'choice_label'=>'name'
        ));
        $builder->add('user', EntityType::class, array(
            'label'=>'form.request.user',
            'class'=>User::class,
            'choice_label'=>function($val, $key, $index){
                return sprintf('%s (%s)',$val->getName(), $val->getLogin());
            }
        ));
        $builder->add('executor', EntityType::class, array(
            'label'=>'form.request.executor',
            'class'=>User::class,
            'choice_label'=>function($val, $key, $index){
                return sprintf('%s (%s)',$val->getName(), $val->getLogin());
            }
        ));

        $builder->add('comments', CommentCollectionType::class, array(
            'label'=>'form.request.comments',
            'allow_add'=>true,
            'allow_delete'=>$options['allow_delete_comments']?:false,
            'by_reference'=>false,
            'entry_type'=>CommentType::class,

        ));
        $builder->add('cancel', Type\SubmitType::class,array(
            'label'=>'form.common.cancel'
        ));
        $builder->add('save', Type\SubmitType::class,array(
            'label'=>'form.common.save'
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefined(array(
            'allow_delete_comments',
            'new_comment_cancel_text',
            'new_comment_submit_text'
        ));
        $resolver->setDefaults(array(
            'allow_delete_comments' => false,
            'translation_domain' => 'forms',
            'new_comment_cancel_text' => 'Cancel',
            'new_comment_submit_text' => 'Submit'
        ));
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['new_comment_cancel_text'] = $options['new_comment_cancel_text'] ;
        $view->vars['new_comment_submit_text'] = $options['new_comment_submit_text'] ;
    }
}